export const FORM_OFFICE_LEVEL = 'FORM_OFFICE_LEVEL';
export const FORM_OFFICE_LABEL = 'FORM_OFFICE_LABEL';
export const FORM_EMPLOYEE_LEVEL = 'FORM_EMPLOYEE_LEVEL';
export const FORM_EMPLOYEE_LABEL = 'FORM_EMPLOYEE_LABEL';
export const FORM_CONTACT_TREE_LEVEL = 'FORM_CONTACT_TREE_LEVEL';
export const FORM_CONTACT_TREE_LABEL = 'FORM_CONTACT_TREE_LABEL';
