export const SLIDESHOW_LEVEL = 'SLIDESHOW_LEVEL';
export const SLIDESHOW_LABEL = 'SLIDESHOW_LABEL';
export const SLIDER_INDEX = 'SLIDER_INDEX';
export const SLIDER_DELAY = 'SLIDER_DELAY';
export const SLIDER_DURATION = 'SLIDER_DURATION';
export const SLIDER_LOOP = 'SLIDER_LOOP';
export const HIGHLIGHTS_LEVEL = 'HIGHLIGHTS_LEVEL';
export const HIGHLIGHTS_LABEL = 'HIGHLIGHTS_LABEL';
