export const SOURCE_SRCSET_DEFAULT = 'SOURCE_SRCSET_DEFAULT';
export const SOURCE_TYPE_PRIMARY = 'SOURCE_TYPE_PRIMARY';
export const SOURCE_SRCSET_PRIMARY = 'SOURCE_SRCSET_PRIMARY';
export const SOURCE_TYPE_SECONDARY = 'SOURCE_TYPE_SECONDARY';
export const SOURCE_SRCSET_SECONDARY = 'SOURCE_SRCSET_SECONDARY';
