export const REQ_HOME_SLIDESHOW = 'REQ_HOME_SLIDESHOW';
export const RCV_HOME_SLIDESHOW = 'RCV_HOME_SLIDESHOW';
export const ERR_HOME_SLIDESHOW = 'ERR_HOME_SLIDESHOW';

export const REQ_HOME_HIGHLIGHTS = 'REQ_HOME_HIGHLIGHTS';
export const RCV_HOME_HIGHLIGHTS = 'RCV_HOME_HIGHLIGHTS';
export const ERR_HOME_HIGHLIGHTS = 'ERR_HOME_HIGHLIGHTS';

export const REQ_PAGE_CONTENT = 'REQ_PAGE_CONTENT';
export const RCV_PAGE_CONTENT = 'RCV_PAGE_CONTENT';
export const ERR_PAGE_CONTENT = 'ERR_PAGE_CONTENT';

export const REQ_CONTACT_DETAILS = 'REQ_CONTACT_DETAILS';
export const RCV_CONTACT_DETAILS = 'RCV_CONTACT_DETAILS';
export const ERR_CONTACT_DETAILS = 'ERR_CONTACT_DETAILS';

export const REQ_FORM_TRANSMIT = 'REQ_FORM_TRANSMIT';
export const RCV_FORM_TRANSMIT = 'RCV_FORM_TRANSMIT';
export const ERR_FORM_TRANSMIT = 'ERR_FORM_TRANSMIT';

export const REQ_FOOTER_SOCIAL = 'REQ_FOOTER_SOCIAL';
export const RCV_FOOTER_SOCIAL = 'RCV_FOOTER_SOCIAL';
export const ERR_FOOTER_SOCIAL = 'ERR_FOOTER_SOCIAL';

export const REQ_FOOTER_SITEMAP = 'REQ_FOOTER_SITEMAP';
export const RCV_FOOTER_SITEMAP = 'RCV_FOOTER_SITEMAP';
export const ERR_FOOTER_SITEMAP = 'ERR_FOOTER_SITEMAP';
